[versions]
pcollectionsVersion = "4.0.1"
junitEngineVersion = "5.10.2"
junitPlatformVersion = "1.10.2"
equalsVerifierVersion = "3.15.8"
mockitoVersion = "5.11.0"
compileTestingVersion = "0.21.0"
sonarVersion = "4.4.1.3373"
versionsVersion = "0.51.0"
nexusVersion = "1.3.0"

[libraries]
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitEngineVersion" }
junitRunner = { group = "org.junit.platform", name = "junit-platform-runner", version.ref = "junitPlatformVersion" }
equalsVerifier = { group = "nl.jqno.equalsverifier", name = "equalsverifier", version.ref = "equalsVerifierVersion" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoVersion" }
mockitoJunit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockitoVersion" }
compileTesting = { group = "com.google.testing.compile", name = "compile-testing", version.ref = "compileTestingVersion" }
pcollections = { group = "org.pcollections", name = "pcollections", version.ref = "pcollectionsVersion" }

[plugins]
sonar = { id = "org.sonarqube", version.ref = "sonarVersion" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsVersion" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusVersion" }